pandas operations

In [11]:
import pandas as pd

In [12]:
df=pd.read_csv("spotify-top-50-world.csv")

In [13]:
print(df)

             date  position                                            song  \
0      2023-05-18         1                                 Ella Baila Sola
1      2023-05-18         2                                       un x100to
2      2023-05-18         3                                 La Bebe - Remix
3      2023-05-18         4                               Cupid - Twin Ver.
4      2023-05-18         5                                         Flowers
...           ...       ...                                             ...
27795  2024-11-27        46  One Of The Girls (with JENNIE, Lily Rose Depp)
27796  2024-11-27        47                            Just the Way You Are
27797  2024-11-27        48                                NIGHTS LIKE THIS
27798  2024-11-27        49                                          Yellow
27799  2024-11-27        50                                Jingle Bell Rock

                                     artist  popularity  duration_ms  \
0                            Eslabon Armado          89       165671
1                Grupo Frontera & Bad Bunny          99       194563
2                    Yng Lvcas & Peso Pluma          99       234352
3                               FIFTY FIFTY          97       174253
4                               Miley Cyrus          91       200600
...                                     ...         ...          ...
27795  The Weeknd & JENNIE & Lily-Rose Depp          89       244684
27796                            Bruno Mars          81       220734
27797                         The Kid LAROI          88        86983
27798                              Coldplay          89       266773
27799                           Bobby Helms          82       130973

      album_type  total_tracks release_date  is_explicit  \
0          album            16   2023-04-28        False
1         single             1   2023-04-17        False
2         single             2   2023-03-17         True
3         single             3   2023-02-24        False
4          album            13   2023-03-10        False
...          ...           ...          ...          ...
27795     single             3   2023-06-23        False
27796      album            12   2010-05-11        False
27797      album            20   2023-11-10        False
27798      album            10   2000-07-10        False
27799     single             2   1957-12-02        False

                                         album_cover_url
0      https://i.scdn.co/image/ab67616d0000b273dfddf1...
1      https://i.scdn.co/image/ab67616d0000b273716c0b...
2      https://i.scdn.co/image/ab67616d0000b273a04be3...
3      https://i.scdn.co/image/ab67616d0000b27337c0b3...
4      https://i.scdn.co/image/ab67616d0000b27358039b...
...                                                  ...
27795  https://i.scdn.co/image/ab67616d0000b273b0dd6a...
27796  https://i.scdn.co/image/ab67616d0000b273f60070...
27797  https://i.scdn.co/image/ab67616d0000b2732abb30...
27798  https://i.scdn.co/image/ab67616d0000b2739164ba...
27799  https://i.scdn.co/image/ab67616d0000b273fd56f3...

[27800 rows x 11 columns]

In [14]:
display(df)

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url
0,2023-05-18,1,Ella Baila Sola,Eslabon Armado,89,165671,album,16,2023-04-28,False,https://i.scdn.co/image/ab67616d0000b273dfddf1...
1,2023-05-18,2,un x100to,Grupo Frontera & Bad Bunny,99,194563,single,1,2023-04-17,False,https://i.scdn.co/image/ab67616d0000b273716c0b...
2,2023-05-18,3,La Bebe - Remix,Yng Lvcas & Peso Pluma,99,234352,single,2,2023-03-17,True,https://i.scdn.co/image/ab67616d0000b273a04be3...
3,2023-05-18,4,Cupid - Twin Ver.,FIFTY FIFTY,97,174253,single,3,2023-02-24,False,https://i.scdn.co/image/ab67616d0000b27337c0b3...
4,2023-05-18,5,Flowers,Miley Cyrus,91,200600,album,13,2023-03-10,False,https://i.scdn.co/image/ab67616d0000b27358039b...
...,...,...,...,...,...,...,...,...,...,...,...
27795,2024-11-27,46,"One Of The Girls (with JENNIE, Lily Rose Depp)",The Weeknd & JENNIE & Lily-Rose Depp,89,244684,single,3,2023-06-23,False,https://i.scdn.co/image/ab67616d0000b273b0dd6a...
27796,2024-11-27,47,Just the Way You Are,Bruno Mars,81,220734,album,12,2010-05-11,False,https://i.scdn.co/image/ab67616d0000b273f60070...
27797,2024-11-27,48,NIGHTS LIKE THIS,The Kid LAROI,88,86983,album,20,2023-11-10,False,https://i.scdn.co/image/ab67616d0000b2732abb30...
27798,2024-11-27,49,Yellow,Coldplay,89,266773,album,10,2000-07-10,False,https://i.scdn.co/image/ab67616d0000b2739164ba...
27799,2024-11-27,50,Jingle Bell Rock,Bobby Helms,82,130973,single,2,1957-12-02,False,https://i.scdn.co/image/ab67616d0000b273fd56f3...

In [15]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url
0,2023-05-18,1,Ella Baila Sola,Eslabon Armado,89,165671,album,16,2023-04-28,False,https://i.scdn.co/image/ab67616d0000b273dfddf1...
1,2023-05-18,2,un x100to,Grupo Frontera & Bad Bunny,99,194563,single,1,2023-04-17,False,https://i.scdn.co/image/ab67616d0000b273716c0b...
2,2023-05-18,3,La Bebe - Remix,Yng Lvcas & Peso Pluma,99,234352,single,2,2023-03-17,True,https://i.scdn.co/image/ab67616d0000b273a04be3...
3,2023-05-18,4,Cupid - Twin Ver.,FIFTY FIFTY,97,174253,single,3,2023-02-24,False,https://i.scdn.co/image/ab67616d0000b27337c0b3...
4,2023-05-18,5,Flowers,Miley Cyrus,91,200600,album,13,2023-03-10,False,https://i.scdn.co/image/ab67616d0000b27358039b...

In [16]:
df.tail()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url
27795,2024-11-27,46,"One Of The Girls (with JENNIE, Lily Rose Depp)",The Weeknd & JENNIE & Lily-Rose Depp,89,244684,single,3,2023-06-23,False,https://i.scdn.co/image/ab67616d0000b273b0dd6a...
27796,2024-11-27,47,Just the Way You Are,Bruno Mars,81,220734,album,12,2010-05-11,False,https://i.scdn.co/image/ab67616d0000b273f60070...
27797,2024-11-27,48,NIGHTS LIKE THIS,The Kid LAROI,88,86983,album,20,2023-11-10,False,https://i.scdn.co/image/ab67616d0000b2732abb30...
27798,2024-11-27,49,Yellow,Coldplay,89,266773,album,10,2000-07-10,False,https://i.scdn.co/image/ab67616d0000b2739164ba...
27799,2024-11-27,50,Jingle Bell Rock,Bobby Helms,82,130973,single,2,1957-12-02,False,https://i.scdn.co/image/ab67616d0000b273fd56f3...

In [17]:
print(df.dtypes)

date               object
position            int64
song               object
artist             object
popularity          int64
duration_ms         int64
album_type         object
total_tracks        int64
release_date       object
is_explicit          bool
album_cover_url    object
dtype: object

In [18]:
df.isnull().sum()

date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
release_date       0
is_explicit        0
album_cover_url    0
dtype: int64